language: php
branches:
  only:
    - master
    - /^.*[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - '7.2'

before_script: composer install
script: phpunit --bootstrap src/autoload.php --test-suffix '-test.php,Test.php,.phpt' tests

notifications:
  email: false

before_deploy:
  - composer phar:install-tools
  - composer install --prefer-dist --no-dev --no-interaction
  - php box.phar build
deploy:
  - provider: releases
    skip_cleanup: true
    file: xml-modules.phar
    api_key:
      secure: "rVpu7NM/Ih9cGqhJ/ywe0XxizPv0il3GlSIJucZnfmw+Y/CNEipTq7pyvhBCSXY/xKtzuxIBmZhVgFmpiAS8dxtQO6e9xohjTQglhPu1SzvYplg0dIT75g/UgqN6WE2tOF16f5z6//cJf7/cLzhILal2tVKs6jIPKFXCryS25z6dkw5rlpL28OUqtu0vLQcBLhHIgHeYKwmOfh1SC2mtY5WyOm/rtha9xCq/bWGzRDs76prUNRENHke//yIDSOU2xxRyHVDK7VArOPMJzknJMYI73yC0fj74lw27zJxOQpQAFbJTY4K25n+SLAdP47DMebQSjtDcQsNn9JB0OwphYNV8KRdK1OOPdkGkvb/PzqGSohU0el+Q2mQAnh4+LUijExXVka6RoB5JMEV/KPQkHrU26IbqpIO3qvZLFQcWX7GaKxXxGRfyi1T/bHbCRDbMvtDC78Bqv3Sw10FM8QU4j8XrUi5yi72ycCU0O71rKfP1CkicPL+DOhhDdLB4COwTb8t7c/wBxOhklg48dS3U8pVSSX75r6Glpb9JtcpaARhByyK1TmGg7cqSTtBMPxkSqGWWg2tDcNsoVkJz3Wr9aR1y4kp9dYufzCHHQ3IOaLJf3RJW3PWNP/qbdt78SDa//ANh/pY87RYEjBm+A76S+j0YL+asTCcljU8yc8P1LUE="
    on:
      repo: bhoogter/xml-modules
      tags: true

